### PR TITLE
🔨 Remove node-red-contrib-actionflows

### LINKED ISSUE #1256: Actionflows no longer working
# Problem/Motivation

After upgrading from 10.3.4 to 10.4.0, [Actionflows](https://github.com/Steveorevo/node-red-contrib-actionflows) stopped working.

## Expected behavior

When an "action" node references an "action in" node, the flow should enter the "action in" node and proceed.

## Actual behavior

The "action in" node is not reached.

## Steps to reproduce

This flow doesn't show any debug message on 10.4.0, but works flawlessly on 10.3.4:
```
[
    {
        "id": "662ae3eeafb188d3",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "10f329202c3aa5dc",
        "type": "inject",
        "z": "662ae3eeafb188d3",
        "name": "prova",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "prova prova prova",
        "payload": "",
        "payloadType": "date",
        "x": 170,
        "y": 200,
        "wires": [
            [
                "a09fd997e2e6357d"
            ]
        ]
    },
    {
        "id": "c5cde19ffa3e6d9c",
        "type": "debug",
        "z": "662ae3eeafb188d3",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 850,
        "y": 200,
        "wires": []
    },
    {
        "id": "6d46a8756417e14d",
        "type": "actionflows_in",
        "z": "662ae3eeafb188d3",
        "name": "action in",
        "priority": "50",
        "links": [],
        "scope": "private",
        "x": 660,
        "y": 200,
        "wires": [
            [
                "c5cde19ffa3e6d9c",
                "7ed722d60c74fc93"
            ]
        ]
    },
    {
        "id": "a09fd997e2e6357d",
        "type": "actionflows",
        "z": "662ae3eeafb188d3",
        "info": "Describe your action API here.",
        "untilproptype": "num",
        "proptype": "msg",
        "name": "action",
        "prop": "loop",
        "untilprop": 0,
        "until": "gt",
        "loop": "none",
        "scope": "private",
        "perf": false,
        "seq": false,
        "x": 350,
        "y": 200,
        "wires": [
            []
        ]
    },
    {
        "id": "7ed722d60c74fc93",
        "type": "actionflows_out",
        "z": "662ae3eeafb188d3",
        "name": "test",
        "links": [],
        "x": 810,
        "y": 320,
        "wires": []
    }
]
```

## Proposed changes

A fix? 😄

### LINKED ISSUE #1258: Restarts everytime pressing Deploy
# Problem/Motivation

> Everytime pressing deploy, NodeRed restarts

This is happening since i updated NodeRed to 10.4.0

## Expected behavior

> only deploy, no restart

## Actual behavior

> Node Red restarts

## Steps to reproduce

> Press Deploy button

LOG says this:

1 Feb 18:42:39 - [info] Stopping modified nodes
1 Feb 18:42:39 - [info] Stopped modified nodes
1 Feb 18:42:39 - [info] Starting modified nodes
1 Feb 18:42:39 - [red] Uncaught Exception:
1 Feb 18:42:39 - [error] TypeError: RED.settings.functionGlobalContext.get is not a function
    at map (/opt/node_modules/node-red-contrib-actionflows/actionflows/actionflows.js:270:51)
    at EventEmitter.runtimeMap (/opt/node_modules/node-red-contrib-actionflows/actionflows/actionflows.js:593:5)
    at EventEmitter.emit (node:events:390:28)
    at start (/opt/node_modules/@node-red/runtime/lib/flows/index.js:383:12)
[18:42:39] INFO: Starting Node-RED...

### PR DESCRIPTION
**Pull request by sinclairpaul**
# Proposed Changes

Remove node-red-contrib-actionflows due to non-maintained and errors

Thought I may aswell PR it, marking as breaking-change as users of the module will be impacted.

Need to follow up to see how many other bundled packages are unmaintained.

## Related Issues

Should fix #1258 fix #1256

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Thanks, @sinclairpaul 👍
