### ISSUE TITLE
Restarts everytime pressing Deploy

### ISSUE THREAD

**Issue by xXDjMikeXx** [hassio-addons/addon-node-red#1258]
# Problem/Motivation

> Everytime pressing deploy, NodeRed restarts

This is happening since i updated NodeRed to 10.4.0

## Expected behavior

> only deploy, no restart

## Actual behavior

> Node Red restarts

## Steps to reproduce

> Press Deploy button

LOG says this:

1 Feb 18:42:39 - [info] Stopping modified nodes
1 Feb 18:42:39 - [info] Stopped modified nodes
1 Feb 18:42:39 - [info] Starting modified nodes
1 Feb 18:42:39 - [red] Uncaught Exception:
1 Feb 18:42:39 - [error] TypeError: RED.settings.functionGlobalContext.get is not a function
    at map (/opt/node_modules/node-red-contrib-actionflows/actionflows/actionflows.js:270:51)
    at EventEmitter.runtimeMap (/opt/node_modules/node-red-contrib-actionflows/actionflows/actionflows.js:593:5)
    at EventEmitter.emit (node:events:390:28)
    at start (/opt/node_modules/@node-red/runtime/lib/flows/index.js:383:12)
[18:42:39] INFO: Starting Node-RED...

**Comment by frenck** [comment]
> 1 Feb 18:42:39 - [error] TypeError: RED.settings.functionGlobalContext.get is not a function
at map (/opt/node_modules/node-red-contrib-actionflows/actionflows/actionflows.js:270:51)
at EventEmitter.runtimeMap (/opt/node_modules/node-red-contrib-actionflows/actionflows/actionflows.js:593:5)

Sounds like an issue with: https://flows.nodered.org/node/node-red-contrib-actionflows

Their issue tracker can be found here: <https://github.com/Steveorevo/node-red-contrib-actionflows/issues>

**Comment by xXDjMikeXx** [comment]
Workaround….downgraded to previous version

**Comment by frenck** [comment]
> Workaround….downgraded to previous version

more importantly, did you report the issue upstream, so it can be fixed?

**Comment by sinclairpaul** [comment]
Further info https://discourse.nodered.org/t/problem-with-node-red-contrib-actionflows-since-upgrade-to-2-2-0/57368

Unless a user reports it to the upstream module it won't get fixed.

**Comment by sinclairpaul** [comment]
Actually reading more into this, actionflows seems to be bundled in the addon, @frenck as it's not maintained, I would say we remove it?

**Comment by Rossez** [comment]
Does disabling those nodes in palette help or do they need to be removed?

**Comment by meks007** [comment]
I have replace all nodes from actionflow nodes to link call nodes and disabled actionflows, but NR keeps restarting all flows instead of just deploying changes.

**Comment by Rossez** [comment]
Then I assume we have to wait for actionflows either to be fixed or maybe better removed from this HA node-red addon. Until then rollback to version 10.3.4.

**Comment by martoq** [comment]
Having this issue as well.  Reported it upstream:

[https://github.com/node-red/node-red/issues/3393](url)

**Comment by Krojack** [comment]
I've never had to rollback an addon before, what's the steps do you take to go back to 10.3.4?

**Comment by martoq** [comment]
> I've never had to rollback an addon before, what's the steps do you take to go back to 10.3.4?

You need to restore from a backup.  I'm in the same boat and don't have a good backup from 10.3.4 (my fault).

**Comment by martoq** [comment]
The issue is the node-red-contrib-actionflows package and it doesn't seem like there is going to be a solution anytime soon based on the chatter upstream.  Is there a chance we can remove this from the package?  It looks like it's hardcoded in and not removeable locally.

![image](https://user-images.githubusercontent.com/11802571/152227327-b3c12b3f-698c-4b88-bab8-b62b11f18fe6.png)

I tried disabling it but still no joy.

**Comment by sinclairpaul** [comment]
Try adding to the config:

```
init_commands: 
    - npm uninstall node-red-contrib-actionflows
 ```

**Comment by martoq** [comment]
Actually I stand corrected.  It "APPEARS" that by disabling the offending npm I have some stability again and it is not craping out.  Required a stop and start on node-red after disabling.

**Comment by meks007** [comment]
I can confirm re-starting node-red after disabling actionflows appears to fix the issue of NR restarting all flows after deploying modifications. Did not try that before, thanks for the heads up.

**Comment by alexanderkrippahl** [comment]
Can also confirm the init_commands work around works. Thank you for sharing!

**Comment by DanNielsen** [comment]
i get this when using the init_commands:
Integration error: init_commands - Integration 'init_commands' not found.
I too have node red restart on every deploy an loose .flow

**Comment by Zahnweh** [comment]
Works for me as well. Thanks a lot! But how do I revert this workaround once the issue is fixed? Just deleting the line from the config?

**Comment by Wzon** [comment]
> Works for me as well. Thanks a lot! But how do I revert this workaround once the issue is fixed? Just deleting the line from the config?

Hopefully there will be a fix from the author. We will have to wait and see. The init_command can be removed once Node-red is restarted.

**Comment by bhyatyab** [comment]
Below is error log I get when hitting deply

`
[08:16:05] INFO: Starting Node-RED...
2022/02/04 08:16:06 [error] 622#622: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "10.0.0.179:8123"
2022/02/04 08:16:07 [error] 622#622: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "10.0.0.179:8123"
2022/02/04 08:16:08 [error] 622#622: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "10.0.0.179:8123"
2022/02/04 08:16:10 [error] 622#622: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "10.0.0.179:8123"
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
2022/02/04 08:16:11 [error] 622#622: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "10.0.0.179:8123"
4 Feb 08:16:19 - [info] 
Welcome to Node-RED
===================
4 Feb 08:16:19 - [info] Node-RED version: v2.2.0
4 Feb 08:16:19 - [info] Node.js  version: v16.13.2
4 Feb 08:16:19 - [info] Linux 5.10.63-v7 arm LE
4 Feb 08:16:24 - [info] Loading palette nodes
4 Feb 08:16:33 - [info] Dashboard version 2.24.0 started at /endpoint/ui
4 Feb 08:16:44 - [info] Settings file  : /etc/node-red/config.js
4 Feb 08:16:44 - [info] Context store  : 'default' [module=memory]
4 Feb 08:16:44 - [info] User directory : /config/node-red/
4 Feb 08:16:44 - [warn] Projects disabled : editorTheme.projects.enabled=false
4 Feb 08:16:44 - [info] Flows file     : /config/node-red/flows.json

`

**Comment by DanNielsen** [comment]
Does this mean that the problem has been fixed? i have updatet but same problem

**Comment by MStcz** [comment]
> Does this mean that the problem has been fixed? i have updatet but same problem

This "Remove node-red-contrib-actionflows due to non-maintained and errors" was accepted by @frenck . I guess it will be fixed in new release of node-red add-on. 10.4.0 is affected version it is necessary to wait for newer one. Till then you can use workaround which was suggested by @sinclairpaul or downgrade to 10.3.4.

init_commands:
- npm uninstall node-red-contrib-actionflows

**Comment by DanNielsen** [comment]
![Udklip](https://user-images.githubusercontent.com/30105329/152520766-fbd0826a-cedb-4840-ab78-ca36dd42e330.JPG)
I can't get it to work i get "ugyldig YAML"?

**Comment by MStcz** [comment]
> > Does this mean that the problem has been fixed? i have updatet but same problem
> 
> This "Remove node-red-contrib-actionflows due to non-maintained and errors" was accepted by @frenck . I guess it will be fixed in new release of node-red add-on. 10.4.0 is affected version it is necessary to wait for newer one. Till then you can use workaround which was suggested by @sinclairpaul or downgrade to 10.3.4.
> 
> ```
> init_commands:
> - npm uninstall node-red-contrib-actionflows
> ```

Missing space before “-“

**Comment by EpicLPer** [comment]
Can confirm that, for now at least, either disabling the Node (via "Manage palette") or outright uninstalling it via the command above both works :)

Since it's going to be removed in future versions directly uninstalling is most likely going to be the better solution either way, yes.

**Comment by Steve-Mcl** [comment]
@Steveorevo has now published a fix for `node-red-contrib-actionflows`
V2.1.2 is now available [in the flows library](https://flows.nodered.org/node/node-red-contrib-actionflows) :+1:

**Comment by cholek3** [comment]
> @Steveorevo has now published a fix for `node-red-contrib-actionflows` V2.1.2 is now available [in the flows library](https://flows.nodered.org/node/node-red-contrib-actionflows) 👍

Updating actionflows to v2.1.2 fixed the problem for me. Kudos to the author. 👍
